### ISSUE TITLE
ClassNotFoundException: ch.qos.logback.core.joran.spi.ElementSelector when used with logback-classic:1.1.2

### ISSUE THREAD

**Issue by timtebeek** [logstash/logstash-logback-encoder#64]
Hi! Tried using logstash-logback-encoder in a basic spring-boot 1.2.0 application, but web deploy to tomcat failed with the following message:
```
Failed to instantiate [ch.qos.logback.classic.LoggerContext]
Reported exception:
java.lang.NoClassDefFoundError: ch/qos/logback/core/joran/spi/ElementSelector
        at ch.qos.logback.classic.joran.JoranConfigurator.addInstanceRules(JoranConfigurator.java:43)
        at ch.qos.logback.core.joran.GenericConfigurator.buildInterpreter(GenericConfigurator.java:116)
        at ch.qos.logback.core.joran.JoranConfiguratorBase.buildInterpreter(JoranConfiguratorBase.java:103)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.joran.spi.ElementSelector
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1711)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1556)
        ... 55 more
```
This might be because spring platform / spring boot comes with logback-classic 1.1.2, something in which I have little choice. Would it be possible for you to support logback-classic:1.1.2?

**Comment by philsttr** [comment]
logstash-logback-encoder does work with logback-classic 1.1.2.

In fact, that's the version that it is built against (see [here](https://github.com/logstash/logstash-logback-encoder/blob/master/pom.xml#L31) ).


If I had to guess, I'd say that the error message you are seeing is caused by a mismatch between logback-core and logback-classic.  Can you ensure that version number of both of those libraries being used is the same?

**Comment by timtebeek** [comment]
Damnit, sorry! For some weird reason a colleague had been using an ancient version of logstash-logback-encoder. Should have checked that first before reporting here, my apologies.
